name: Run Nginx

on:
    push:
        branches:
            - main

jobs:
    build:
        runs-on: self-hosted

        steps:
            - name: Checkout code
                uses: actions/checkout@v2

            - name: Install Docker
                run: |
                    sudo apt-get update
                    sudo apt-get install -y docker.io

            - name: Start Docker Compose
                run: |
                    docker-compose up -d