name: Run Nginx

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Docker
        run: |
            # sudo apt-get remove update-manager
            # sudo apt-get --purge remove lubuntu-update-notifier
            sudo snap refresh snapd-desktop-integration --stable
            sudo apt-get update
            sudo apt-get upgrade -y && sudo apt-get dist-upgrade -y

      - name: Start Docker Compose
        run: |
            docker compose up -d
            sudo reboot
            # nohup bash -c "sleep 10 && sudo reboot" >/dev/null 2>&1 &