name: Run Nginx

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Docker
        run: |
            # sudo apt-get remove update-manager
            # sudo apt-get --purge remove lubuntu-update-notifier
            sudo apt-get update
            sudo apt-get upgrade -y && sudo apt-get dist-upgrade -y

      - name: Start Docker Compose
        run: |
            docker compose up -d
            echo 'until curl http://localhost; do echo "Retrying in 5 seconds..."; sleep 5; done" > cat ~/Desktop/wait-for-nginx.sh'
            sudo reboot
            # nohup bash -c "sleep 20 && sudo reboot" >/dev/null 2>&1 &